In [1]:
import pandas as pd
from nba_api.stats.endpoints import playercareerstats, teamyearbyyearstats, commonallplayers

In [8]:
pd.set_option('display.max_columns', 40)
pd.set_option('display.max_rows', 40)
career = playercareerstats.PlayerCareerStats(player_id='203076', per_mode36="Per36")


career.get_data_frames()[0].iloc[-1:]

,PLAYER_ID,SEASON_ID,LEAGUE_ID,TEAM_ID,TEAM_ABBREVIATION,PLAYER_AGE,GP,GS,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS
8,203076,2020-21,00,1610612747,LAL,28.0,23,23,755.0,9.7,18.3,0.533,0.8,2.8,0.293,4.4,6.2,0.715,2.2,7.0,9.2,3.3,1.5,2.0,2.1,2.0,24.7

In [15]:
#team = teamyearbyyearstats.TeamYearByYearStats(team_id='1610612739', season_type_all_star='Regular Season', per_mode_simple='PerGame')
#team.get_data_frames()[0]

players = commonallplayers.CommonAllPlayers(season='2020-21',is_only_current_season=1)
players = players.get_data_frames()[0]

cond1 = players['GAMES_PLAYED_FLAG']=="Y"
cond2 = players['ROSTERSTATUS']==1
cond = cond1 & cond2
players[cond]

,PERSON_ID,DISPLAY_LAST_COMMA_FIRST,DISPLAY_FIRST_LAST,ROSTERSTATUS,FROM_YEAR,TO_YEAR,PLAYERCODE,TEAM_ID,TEAM_CITY,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CODE,GAMES_PLAYED_FLAG,OTHERLEAGUE_EXPERIENCE_CH
0,1630173,"Achiuwa, Precious",Precious Achiuwa,1,2020,2020,precious_achiuwa,1610612748,Miami,Heat,MIA,heat,Y,00
2,203500,"Adams, Steven",Steven Adams,1,2013,2020,steven_adams,1610612740,New Orleans,Pelicans,NOP,pelicans,Y,00
3,1628389,"Adebayo, Bam",Bam Adebayo,1,2017,2020,bam_adebayo,1610612748,Miami,Heat,MIA,heat,Y,00
4,200746,"Aldridge, LaMarcus",LaMarcus Aldridge,1,2006,2020,lamarcus_aldridge,1610612751,Brooklyn,Nets,BKN,nets,Y,00
5,1630234,"Alexander, Ty-Shon",Ty-Shon Alexander,1,2020,2020,ty-shon_alexander,1610612756,Phoenix,Suns,PHX,suns,Y,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
511,1626153,"Wright, Delon",Delon Wright,1,2015,2020,delon_wright,1610612758,Sacramento,Kings,SAC,kings,Y,01
512,201152,"Young, Thaddeus",Thaddeus Young,1,2007,2020,thaddeus_young,1610612741,Chicago,Bulls,CHI,bulls,Y,00
513,1629027,"Young, Trae",Trae Young,1,2018,2020,trae_young,1610612737,Atlanta,Hawks,ATL,hawks,Y,00
514,203469,"Zeller, Cody",Cody Zeller,1,2013,2020,cody_zeller,1610612766,Charlotte,Hornets,CHA,hornets,Y,00
515,1627826,"Zubac, Ivica",Ivica Zubac,1,2016,2020,ivica_zubac,1610612746,LA,Clippers,LAC,clippers,Y,01